namespace WindowsClientCenter.Intune.Services.Models;

public sealed record LocalIntuneSnapshot(
    string Host,
    string MachineName,
    DateTimeOffset CapturedAt,
    bool IsLocalHost,
    string LastSyncText,
    string RegistrationSummary,
    string DsregStatusText,
    IReadOnlyList<string> DsregHighlights,
    IReadOnlyList<EnrollmentArtifact> EnrollmentArtifacts,
    IReadOnlyList<string> EnterpriseMgmtTasks,
    IReadOnlyList<string> CertificateSummaries,
    IReadOnlyList<NameValueItem> ServiceValues,
    IReadOnlyList<string> Notes,
    string MdmLastSyncText = "Unknown",
    string ImeLastSyncText = "Unknown",
    string WindowsVersionText = "Unknown",
    string WindowsBuildText = "Unknown",
    string FreeDiskSpaceText = "Unknown",
    string PatchStatusText = "Patch status unavailable.",
    string PatchStatusLevel = "Unknown",
    DeliveryOptimizationSnapshot? DeliveryOptimization = null,
    PlatformSecuritySnapshot? PlatformSecurity = null,
    SystemRuntimeSnapshot? SystemRuntime = null,
    NetworkConnectivitySnapshot? NetworkConnectivity = null,
    string ManufacturerText = "Unknown",
    string ModelText = "Unknown",
    string SerialNumberText = "Unknown",
    string AdJoinPathText = "Unknown",
    string UpdateRingText = "Unknown");
